import { getAllDayTaskIds } from "./daily-plans.js";

/** 12-Wochen Sprint — Qualifikation für ML/DL-Stellen (😊-Fokus) */

export const PLAN = {
  title: "12-Wochen Sprint: ML/DL → 😊 & Medizin-KI",
  subtitle: "Vollzeit · PyTorch · CV · Speech/NLP · Pipeline · Deploy — ohne IfaDW-Breite",
  phases: [
    { id: "a", name: "Phase A", label: "Engineering + sklearn", weeks: [1, 2] },
    { id: "b", name: "Phase B", label: "Computer Vision (PyTorch)", weeks: [3, 4, 5] },
    { id: "c", name: "Phase C", label: "NLP & Spracherkennung", weeks: [6, 7] },
    { id: "d", name: "Phase D", label: "Pipeline + TensorFlow", weeks: [8] },
    { id: "e", name: "Phase E", label: "Signature Medizin-KI", weeks: [9, 10] },
    { id: "f", name: "Phase F", label: "Bewerbung 😊", weeks: [11, 12] },
  ],
  dailyRhythm: [
    { time: "09:00–10:30", activity: "Theorie / Tutorial / Paper skim" },
    { time: "10:45–12:30", activity: "Hands-on Coding / Training" },
    { time: "12:30–13:30", activity: "Pause" },
    { time: "13:30–15:30", activity: "Projekt — Pipeline oder Modell" },
    { time: "15:45–17:00", activity: "Eval, Tests, README, Commit" },
    { time: "17:00–17:30", activity: "Optional: Interview-Notiz, Paper" },
  ],
  techStack: [
    { category: "Sprache", choice: "Python 3.11+, Type Hints, pytest" },
    { category: "Klassisches ML", choice: "scikit-learn (Baseline + Metriken)" },
    { category: "Deep Learning", choice: "PyTorch (Hauptpfad) + TensorFlow/Keras (Pflicht-Kennnis)" },
    { category: "Computer Vision", choice: "torchvision, Transfer Learning, HAM10000" },
    { category: "NLP / Speech", choice: "spaCy, Whisper (faster-whisper), Hugging Face Basics" },
    { category: "API & Deploy", choice: "FastAPI, Docker, GitHub Actions, Railway/Render" },
    { category: "Linux", choice: "Bash, grep, Pipeline-Skripte" },
    { category: "Tracking", choice: "MLflow (Experimente)" },
    { category: "Eval", choice: "F1, Precision, Recall, ROC — medizinische Metriken" },
  ],
  targetRole: {
    company: "😊",
    url: "https://example.com/medtech-ml-jobs",
    focus: ["Spracherkennung (Ärzte)", "Lesionsklassifikation (Melanom/CV)", "Volle Pipeline bis Deploy", "PyTorch, TensorFlow, sklearn"],
  },
  weeks: [
    {
      number: 1,
      title: "Python Engineering + Git",
      focus: "Sauberer Code — Voraussetzung bei 😊",
      outcome: "Repo mit Tests und CI-Grundlage",
      learn: ["Modern Python, pytest, Git workflow", "FastAPI Grundlagen", "Projektstruktur für ML-Services"],
      tasks: [
        "Repo medizin-ml-portfolio anlegen",
        "FastAPI /health + pytest",
        "Type Hints + Modulstruktur app/",
        "Git: Branch, PR, sinnvolle Commits",
        "README: Setup in 3 Befehlen",
      ],
      milestone: "Engineering-Basis auf GitHub — kein Notebook-only",
      resources: [],
    },
    {
      number: 2,
      title: "sklearn Baseline + ML-API deployt",
      focus: "Klassisches ML + Deployment (Recruiter-Häkchen)",
      outcome: "Live ML-API mit Eval-Report",
      learn: ["Train/Test, F1, Confusion Matrix", "sklearn Pipeline + joblib", "Docker + Cloud Deploy"],
      tasks: [
        "Tabular Dataset (Healthcare wenn möglich)",
        "Baseline Classifier + Cross-Val",
        "POST /predict FastAPI",
        "Confusion Matrix + F1 im README",
        "Docker + Live-URL",
      ],
      milestone: "ML-API live — zeigt Pipeline-Denken",
      resources: [],
    },
    {
      number: 3,
      title: "PyTorch Grundlagen",
      focus: "Training Loop — Pflicht für 😊",
      outcome: "Trainiertes Modell + Checkpoint",
      learn: ["Tensors, autograd, DataLoader", "Training Loop: forward, loss, backward", "GPU/MPS, Overfitting erkennen"],
      tasks: [
        "PyTorch Tutorial + MNIST oder med. Tabular NN",
        "Training/Val Loss plotten",
        "Checkpoint save/load",
        "Training Loop auswendig erklären können",
        "Unit Test für Preprocessing",
      ],
      milestone: "5 Schritte Training Loop ohne Spickzettel",
      resources: [],
    },
    {
      number: 4,
      title: "CNNs + Transfer Learning (Lesion/CV)",
      focus: "Direkt 😊: Bildklassifikation Melanom/Läsion",
      outcome: "Fine-tuned CNN mit medizinischen Metriken",
      learn: ["CNN Architektur, Augmentation", "Transfer Learning ResNet/EfficientNet", "Unbalanced classes: F1, Weighted Loss"],
      tasks: [
        "HAM10000 oder ISIC Dataset laden",
        "ResNet18 fine-tunen + Augmentation",
        "Precision/Recall pro Klasse",
        "Confusion Matrix + ROC",
        "Bestes Modell als .pt speichern",
      ],
      milestone: "CV-Modell schlägt Baseline — Metriken dokumentiert",
      resources: [],
    },
    {
      number: 5,
      title: "CV Inference API deployt",
      focus: "Bild → Prediction in Production",
      outcome: "Live CV-API (😊-Kernkompetenz)",
      learn: ["FastAPI File Upload, Bild-Preprocessing", "torch.no_grad Inference", "Docker mit Modell-Volume"],
      tasks: [
        "POST /predict/image mit Confidence + Top-K",
        "Preprocessing Pipeline (resize, normalize)",
        "Docker + docker-compose",
        "10 Testbilder + Fehleranalyse",
        "Live Deploy + Demo-GIF im README",
      ],
      milestone: "CV-API live — Hauptprojekt für 😊-Gespräch",
      resources: [],
    },
    {
      number: 6,
      title: "spaCy + medizinisches NLP",
      focus: "NLP-Pipeline (Spracherkennung vorbereiten)",
      outcome: "NER/Batch-Pipeline auf DE-Text",
      learn: ["spaCy Pipeline, NER, Custom Rules", "Medizinische Begriffe / Abkürzungen", "Batch-Verarbeitung"],
      tasks: [
        "spaCy de_core_news_sm + NER Demo",
        "Custom Entity Rules (Medizin optional)",
        "Batch JSON Export aus Textordner",
        "Precision/Recall auf kleinem Gold-Set",
        "nlp-pipeline Modul + Tests",
      ],
      milestone: "NLP-Pipeline auf GitHub",
      resources: [],
    },
    {
      number: 7,
      title: "Whisper ASR — medizinisches Diktat",
      focus: "Direkt 😊: Spracherkennung für Ärzte",
      outcome: "Audio → Text API",
      learn: ["Whisper / faster-whisper", "Audio Upload, Chunking lange Dateien", "Post-Processing, Latenz"],
      tasks: [
        "Whisper DE transkribieren (3+ Samples)",
        "FastAPI POST /transcribe",
        "Optional: Wörterbuch Post-Correction",
        "Latenz + Qualität dokumentieren",
        "Docker + lokaler compose Stack",
      ],
      milestone: "Speech-API funktioniert — zweites 😊-Häkchen",
      resources: [],
    },
    {
      number: 8,
      title: "Volle Pipeline + TensorFlow + MLflow",
      focus: "Daten → Modell → Track → Deploy (Stellenanzeige wörtlich)",
      outcome: "End-to-end Pipeline + TF-Modell + MLflow",
      learn: ["Bash: Daten download → preprocess", "TensorFlow/Keras: 1 Modell (MNIST oder Tabular)", "MLflow Experiment Tracking", "Linux CLI Essentials"],
      tasks: [
        "Bash-Script Daten-Pipeline",
        "Keras Modell trainieren (Vergleich zu PyTorch)",
        "MLflow: 3 Runs loggen",
        "Pipeline-Diagramm (Mermaid) im README",
        "TensorFlow vs PyTorch Notiz (1 Seite)",
      ],
      milestone: "Pipeline + MLflow + TF — alle Stellen-Keywords abgedeckt",
      resources: [],
    },
    {
      number: 9,
      title: "Signature-Projekt I — Architektur & Training",
      focus: "Medizin-KI Flagship (CV oder Speech)",
      outcome: "Trainiertes Flagship-Modell + Eval",
      learn: ["Projekt wählen: Lesion-Klassifikator ODER Diktat+NER Pipeline", "Eval-Report für Stakeholder", "Design Decisions dokumentieren"],
      tasks: [
        "Projektspec: Anforderungen + Architektur",
        "Datenakquise + Aufbereitung",
        "Training + Hyperparameter",
        "Eval: F1, Confusion, Error Analysis (20 Fails)",
        "MLflow Run + Modell Registry",
      ],
      milestone: "Flagship-Modell evaluiert — bereit für Deploy",
      resources: [],
    },
    {
      number: 10,
      title: "Signature-Projekt II — Deploy & Demo",
      focus: "Production-ready Medizin-KI Service",
      outcome: "Live URL + 5-Min Demo",
      learn: ["Docker Production, Health Checks", "Structured Logging", "Demo für Bewerbungsgespräch"],
      tasks: [
        "FastAPI Production (rate limit, /health)",
        "Docker + Live Deploy",
        "GitHub Actions CI",
        "5-Min Loom: Pipeline Walkthrough",
        "README: Metriken, Ethik (Bias, Datenschutz), Setup",
      ],
      milestone: "Signature-Projekt live — Bewerbungs-Highlight",
      resources: [],
    },
    {
      number: 11,
      title: "Portfolio + 😊-Vorbereitung",
      focus: "3 Repos + Anschreiben",
      outcome: "Bewerbungsmappe fertig",
      learn: ["GitHub Pins, einheitliche READMEs", "😊 Stellenprofil spiegeln", "Medizin-KI Motivation"],
      tasks: [
        "Repos polieren: ML-API, CV-API, Speech/NLP",
        "Signature-Repo pinnen",
        "Anschreiben 😊 (DE, C1)",
        "Lebenslauf: Projekte vor Weiterbildung",
        "LinkedIn Headline: ML/DL / Medizin-KI",
      ],
      milestone: "Anschreiben + CV fertig für 😊",
      resources: [],
    },
    {
      number: 12,
      title: "Interview + Bewerbung",
      focus: "😊 bewerben + Gespräch üben",
      outcome: "Bewerbung raus, interview-ready",
      learn: [
        "Interview: CNN, ASR, Pipeline, PyTorch, TF",
        "5-Min Pitches: CV-Projekt + Speech-Projekt",
        "Fragen zu Medizin-KI, Team, sauberem Code",
      ],
      tasks: [
        "15 Interview-Fragen schriftlich (DE)",
        "5-Min CV-API Pitch üben (3×)",
        "5-Min Speech-Pipeline Pitch üben (3×)",
        "Bewerbung 😊 + 5 ähnliche Stellen",
        "Mock Interview (selbst oder Partner)",
      ],
      milestone: "😊-Bewerbung verschickt",
      resources: [],
    },
  ],
  finalChecklist: [
    "CV-Lesion-API live (HAM10000 o.ä.) mit F1/Recall im README",
    "Speech/Whisper-API oder Diktat-Pipeline demo-fähig",
    "sklearn ML-API deployt (Pipeline-Denken)",
    "TensorFlow/Keras: mind. 1 trainiertes Modell",
    "MLflow: Experiment + bestes Modell geloggt",
    "Signature-Projekt: Live-URL + 5-Min Demo-Video",
    "Bash-Datenpipeline-Script",
    "Anschreiben 😊 + Lebenslauf DE",
    "15 Interview-Fragen beantwortet",
    "Deutsch C1 im Gespräch üben (Fachbegriffe erklären)",
  ],
  interviewQuestions: [
    "Beschreibe die volle KI-Pipeline von Rohdaten bis Deployment — wie bei 😊.",
    "Wie würdest du ein Modell zur Lesionsklassifikation (Melanom) evaluieren?",
    "Precision vs. Recall — warum in der Medizin oft Recall wichtiger?",
    "Erkläre dein CNN-Projekt: Architektur, Augmentation, Metriken.",
    "Wie funktioniert Transfer Learning und wann nutzt du es?",
    "PyTorch Training Loop — die 5 Schritte?",
    "Unterschied PyTorch vs. TensorFlow — wann was?",
    "Wie würdest du Whisper für medizinische Diktate einsetzen? Grenzen?",
    "Was ist Data Leakage — Beispiel bei medizinischen Bilddaten?",
    "Wie sicherst du sauberen, wartbaren ML-Code?",
    "SHAP oder Error Analysis — wie erklärst du Modellfehler?",
    "Wie deployest du ein PyTorch-Modell in FastAPI?",
    "Was weißt du über Spracherkennung bei 😊 (Ärzte)?",
    "Wie gehst du mit unbalancierten Klassen in CV um?",
    "5-Min Walkthrough deines Signature-Projekts.",
  ],
};

export function getAllTaskIds() {
  const ids = [...getAllDayTaskIds()];
  for (const week of PLAN.weeks) {
    ids.push(`w${week.number}-milestone`);
  }
  for (let i = 0; i < PLAN.finalChecklist.length; i++) {
    ids.push(`final-${i}`);
  }
  return ids;
}
