import { getAllDayTaskIds } from "./daily-plans.js";

export const PLAN = {
  title: "12-Wochen Vollzeit-Plan: LLM/RAG → KI-Entwickler",
  subtitle: "35–40 Stunden/Woche · Fokus LLM/RAG · Aufbau auf Data Science (2022)",
  phases: [
    {
      id: "a",
      name: "Phase A",
      label: "Engineering-Minimum",
      weeks: [1, 2],
    },
    {
      id: "b",
      name: "Phase B",
      label: "LLM-Grundlagen",
      weeks: [3, 4],
    },
    {
      id: "c",
      name: "Phase C",
      label: "RAG Deep Dive",
      weeks: [5, 6, 7],
    },
    {
      id: "d",
      name: "Phase D",
      label: "Agents & Production",
      weeks: [8, 9],
    },
    {
      id: "e",
      name: "Phase E",
      label: "Portfolio & Bewerbung",
      weeks: [10, 11, 12],
    },
  ],
  dailyRhythm: [
    { time: "09:00–10:30", activity: "Theorie / Kurs / Docs lesen" },
    { time: "10:45–12:30", activity: "Hands-on Coding" },
    { time: "12:30–13:30", activity: "Pause" },
    { time: "13:30–15:30", activity: "Projektarbeit" },
    { time: "15:45–17:00", activity: "Debugging, README, Tests" },
    { time: "17:00–17:30", activity: "Optional: LinkedIn, Blog-Notiz, Wiederholung" },
  ],
  techStack: [
    { category: "Sprache", choice: "Python 3.11+" },
    { category: "API", choice: "FastAPI" },
    { category: "LLM", choice: "OpenAI API + Ollama (lokal)" },
    { category: "RAG Framework", choice: "LlamaIndex oder LangChain" },
    { category: "Vektordatenbank", choice: "Qdrant oder Chroma" },
    { category: "Embeddings", choice: "text-embedding-3-small + Open Source" },
    { category: "Frontend (Demo)", choice: "Streamlit" },
    { category: "Container", choice: "Docker + docker-compose" },
    { category: "Deploy", choice: "Railway / Fly.io / Render" },
    { category: "Eval", choice: "RAGAS + manuelles Test-Set" },
    { category: "Observability", choice: "Langfuse oder simples Logging" },
  ],
  weeks: [
    {
      number: 1,
      title: "Python modern + FastAPI",
      focus: "Engineering-Basis statt Notebook-only",
      outcome: "ML-Endpoint live",
      learn: [
        "Python: Type Hints, dataclasses, pathlib, virtuelle Env (uv/poetry)",
        "Git: Branch, PR, sinnvolle Commits",
        "FastAPI: Routes, Pydantic-Models, Dependency Injection",
      ],
      tasks: [
        "FastAPI-Tutorial Tag 1–3 durcharbeiten",
        "sklearn-Klassifikator auf Public Dataset trainieren",
        "POST /predict Endpoint mit JSON-Input bauen",
        "Modell beim Start laden (nicht pro Request neu trainieren)",
        "OpenAPI-Docs unter /docs testen",
        "GitHub-Repo anlegen mit README",
      ],
      milestone: "API lokal lauffähig, GitHub-Repo mit README",
      resources: ["https://fastapi.tiangolo.com/tutorial/"],
    },
    {
      number: 2,
      title: "Docker + Deployment",
      focus: "Deploybar, nicht nur lokal",
      outcome: "Deploybares ML-API-Repo",
      learn: [
        "Dockerfile (Multi-Stage optional)",
        "docker-compose für lokale Services",
        "GitHub Actions: Lint + Test bei Push",
        "Deployment auf Railway, Fly.io oder Render",
      ],
      tasks: [
        "ML-API in Dockerfile packen",
        "docker-compose für lokale Entwicklung",
        "GitHub Actions CI einrichten",
        "Auf Railway/Fly.io/Render deployen",
        "README: Architektur-Skizze (Mermaid)",
        "README: Setup in 3 Befehlen + curl-Beispiel",
      ],
      milestone: "Live-URL im README — erster Recruiter-Häkchen-Punkt",
      resources: [],
    },
    {
      number: 3,
      title: "LLM-APIs & Prompt Engineering",
      focus: "Sicher mit OpenAI-kompatiblen APIs arbeiten",
      outcome: "Chat-App mit System-Prompts",
      learn: [
        "Chat Completions vs. Completions",
        "System / User / Assistant Messages",
        "Temperature, max_tokens, Streaming",
        "Few-Shot, Chain-of-Thought (CoT)",
        "Structured Output (JSON mode / Function Calling Grundlagen)",
      ],
      tasks: [
        "OpenAI API Account + Budget-Limit setzen",
        "Ollama installieren (Llama 3, Mistral)",
        "Prompt-Lab-App bauen (Streamlit oder FastAPI)",
        "Verschiedene System-Prompts testen",
        "Streaming-Antworten implementieren",
        "Token-/Kosten-Schätzung pro Request",
      ],
      milestone: "Token & Kosten mündlich erklären können",
      resources: [],
    },
    {
      number: 4,
      title: "Embeddings & Vektorsuche",
      focus: "Herzstück von RAG vor dem Framework",
      outcome: "Semantische Suche funktioniert",
      learn: [
        "Embeddings, Vektor-Raum, Cosine Similarity",
        "Embedding-Modelle: text-embedding-3-small, bge-small",
        "Chunking: Fixed size, overlap, semantic (Überblick)",
        "Vektordatenbanken: Chroma oder Qdrant",
      ],
      tasks: [
        "20–50 Markdown/PDF-Dateien sammeln",
        "Embeddings manuell berechnen und speichern",
        "Semantische Suche: Query → Top-5 Chunks mit Score",
        "CLI oder minimales UI bauen",
        "Chunk-Größe und Overlap experimentieren",
      ],
      milestone: "Chunk-Größe und Overlap-Einfluss erklären können",
      resources: [],
    },
    {
      number: 5,
      title: "RAG von Grund auf",
      focus: "Klassische RAG-Pipeline verstehen und bauen",
      outcome: "Einfacher Doc-Chatbot",
      learn: [
        "Pipeline: Docs → Chunking → Embeddings → Vector Store",
        "Query → Embedding → Retrieval → Context + Prompt → LLM",
        "LlamaIndex oder LangChain (eins wählen!)",
      ],
      tasks: [
        "Framework wählen: LlamaIndex oder LangChain",
        "PDF/Markdown Upload implementieren",
        "Doc-Q&A-Bot mit Quellenangabe (Chunk + Seitenzahl)",
        "FastAPI-Backend + Streamlit-Frontend",
        "Bot sagt „weiß ich nicht“ wenn nichts passt",
      ],
      milestone: "RAG-Bot antwortet nur aus Dokumenten",
      resources: ["https://huggingface.co/learn/nlp-course"],
    },
    {
      number: 6,
      title: "RAG Advanced",
      focus: "Unterschied zu Tutorial-RAG",
      outcome: "Hybrid Search, Metadata, besseres Chunking",
      learn: [
        "Hybrid Search: BM25 + Vector",
        "Metadata Filtering (z. B. nur Docs aus 2024)",
        "Re-Ranking: Cross-Encoder oder Cohere Rerank",
        "Query Transformation: HyDE, Multi-Query",
        "Parent-Child Chunking",
      ],
      tasks: [
        "Hybrid Search implementieren",
        "Metadata Filtering hinzufügen",
        "Mind. 1 Query Transformation (HyDE oder Multi-Query)",
        "Parent-Child Chunking testen",
        "Konfiguration über .env (Model, Chunk Size, Top-K)",
        "README: Design Decisions dokumentieren",
      ],
      milestone: "README mit Design Decisions — A/B Chunking dokumentiert",
      resources: [],
    },
    {
      number: 7,
      title: "Evaluation & Observability",
      focus: "Qualität messen, nicht nur bauen",
      outcome: "RAG mit Metriken + Logging",
      learn: [
        "RAG-Metriken: Context Precision/Recall, Faithfulness, Answer Relevance",
        "RAGAS oder manuelles Eval-Set",
        "Logging: Langfuse, LangSmith oder JSON-Logging",
        "Tracing: Was wurde retrieved? Welcher Prompt?",
      ],
      tasks: [
        "15 Testfragen mit erwarteten Quellen erstellen",
        "RAGAS oder manuelle Eval-Pipeline aufsetzen",
        "Precision@3 und Antwortqualität messen",
        "Logging/Tracing für Retrieval + Prompt",
        "Ergebnisse-Tabelle im README",
        "Chunk-Size Optimierung basierend auf Eval",
      ],
      milestone: "Eval-Ergebnisse im README, Interview-Antwort vorbereitet",
      resources: [],
    },
    {
      number: 8,
      title: "Agents & Tool Use",
      focus: "Über reinen Doc-Chat hinaus",
      outcome: "Agent mit min. 2 Tools",
      learn: [
        "Function Calling / Tool Use",
        "ReAct-Pattern (Reason + Act)",
        "Wann Agent vs. feste Pipeline?",
      ],
      tasks: [
        "Research Agent planen",
        "Tool 1: Websuche (Tavily/SerpAPI) oder RAG",
        "Tool 2: Rechner, DB oder Kalender",
        "Max. Iterationen, Timeout, Kostenlimit setzen",
        "Agent nutzt Tools sinnvoll (keine Endlosschleifen)",
      ],
      milestone: "Research Agent mit Quellen-Zusammenfassung",
      resources: [],
    },
    {
      number: 9,
      title: "Production Readiness",
      focus: "Kosten, Latenz, Fehler wie echte Teams",
      outcome: "Optimiertes RAG-System",
      learn: [
        "Caching: Embedding-Cache, LLM-Response-Cache",
        "Rate Limiting & API-Keys",
        "Async Requests, Streaming für UX",
        "Fallback: Primary LLM down → Secondary",
        "Kostenkontrolle: Batch-Embeddings, kleinere Modelle",
      ],
      tasks: [
        "Streaming-Antworten im RAG-System",
        "Caching-Layer (Redis oder in-memory)",
        "Rate Limit implementieren",
        "Fallback-Modell konfigurieren",
        "Docker-Compose: App + Qdrant + Redis",
      ],
      milestone: "System fühlt sich produktionsnah an",
      resources: [],
    },
    {
      number: 10,
      title: "Signature-Projekt",
      focus: "Enterprise Knowledge Assistant",
      outcome: "Vollständige App, deployt",
      learn: [
        "Multi-Format Upload (PDF, MD, DOCX)",
        "Hybrid RAG + Quellenangabe + Eval-Report",
        "Admin: Dokumente neu indexieren",
      ],
      tasks: [
        "Multi-Format Upload implementieren",
        "Hybrid RAG + Quellenangabe integrieren",
        "Eval-Report ins Repo",
        "FastAPI + Docker + Live-Deploy",
        "Admin-Endpoint: Dokumente neu indexieren",
        "USP wählen: DE/EN-Corpus, Domäne, oder Doc-Vergleich",
        "5-Min Demo-Video (Loom) — Link im README",
      ],
      milestone: "Demo-URL + Video-Walkthrough im README",
      resources: [],
    },
    {
      number: 11,
      title: "Portfolio & Sichtbarkeit",
      focus: "3 Repos polieren, LinkedIn, Lebenslauf",
      outcome: "3 GitHub-Repos poliert",
      learn: [
        "GitHub-Repos professionell präsentieren",
        "LinkedIn-Profil optimieren",
        "Lebenslauf: Projekte vor Weiterbildung",
      ],
      tasks: [
        "Repo 1 (ML-API): README, Screenshots, .env.example",
        "Repo 2 (RAG-System): Architektur-Diagramm, Eval",
        "Repo 3 (Research Agent): Setup < 5 Minuten",
        "LinkedIn Headline + About aktualisieren",
        "2 LinkedIn-Posts über RAG-Learnings",
        "Lebenslauf: Projekte 2025/2026 mit Links",
      ],
      milestone: "LinkedIn + Lebenslauf fertig, 3 Repos poliert",
      resources: [],
    },
    {
      number: 12,
      title: "Bewerbungen + Interview-Prep",
      focus: "Erste Bewerbungen, Top-10-Fragen",
      outcome: "Erste Bewerbungen raus",
      learn: [
        "Typische Interview-Fragen für LLM/RAG",
        "Leichtes Coding-Prep (Python, FastAPI)",
        "5-Min Projekt-Pitch",
      ],
      tasks: [
        "10–15 gezielte Bewerbungen senden",
        "Top 10 Interview-Fragen beantworten können",
        "5-Min Signature-Projekt-Pitch üben",
        "Python/FastAPI Coding kurz auffrischen",
        "Suchbegriffe: KI-Entwickler, LLM Engineer, GenAI Developer",
      ],
      milestone: "Erste Bewerbungen verschickt, Pitch geübt",
      resources: [],
    },
  ],
  finalChecklist: [
    "Signature-Projekt live deployt",
    "RAG mit Quellenangabe + Eval-Report",
    "3 GitHub-Repos mit professionellen READMEs",
    "Docker für mindestens 2 Projekte",
    "5-Min-Projekt-Pitch geübt",
    "LinkedIn + Lebenslauf aktualisiert",
    "10 Interview-Fragen beantworten können",
  ],
  interviewQuestions: [
    "Erkläre RAG in 2 Minuten.",
    "Wann RAG vs. Fine-Tuning?",
    "Wie wählst du Chunk-Size?",
    "Was ist Embedding Drift?",
    "Wie misst du Halluzinationen?",
    "Wie senkst du LLM-Kosten?",
    "Unterschied Vector Search vs. Keyword Search?",
    "Was passiert bei 100.000 PDFs?",
    "Wie sicherst du API-Keys?",
    "Walkthrough deines Signature-Projekts (5 Min.)",
  ],
};

export function getAllTaskIds() {
  const ids = [...getAllDayTaskIds()];
  for (const week of PLAN.weeks) {
    ids.push(`w${week.number}-milestone`);
  }
  for (let i = 0; i < PLAN.finalChecklist.length; i++) {
    ids.push(`final-${i}`);
  }
  return ids;
}
