/** Detaillierte Lernressourcen — wie & wo lernen */

export const TUTORIAL_TYPES = {
  docs: "Dokumentation",
  video: "Video",
  course: "Kurs",
  book: "Buch",
  article: "Artikel",
  tool: "Tool",
};

export const GLOBAL_RESOURCES = [
  {
    id: "github-skills",
    title: "GitHub Skills",
    url: "https://skills.github.com/",
    type: "course",
    cost: "Kostenlos",
    duration: "2–4 h",
    description: "Interaktive Git/GitHub-Übungen direkt im Browser — ideal zum Auffrischen.",
  },
  {
    id: "real-python",
    title: "Real Python",
    url: "https://realpython.com/",
    type: "article",
    cost: "Teils kostenlos",
    duration: "Nach Bedarf",
    description: "Hochwertige Python-Artikel — suche gezielt nach Type Hints, pytest, pathlib.",
  },
  {
    id: "deeplearning-ai",
    title: "DeepLearning.AI Short Courses",
    url: "https://www.deeplearning.ai/short-courses/",
    type: "course",
    cost: "Kostenlos",
    duration: "1–2 h pro Kurs",
    description: "Kurze Kurse zu LLMs, RAG, Agents — mit Andrew Ng / OpenAI / LangChain.",
  },
];

/** Woche → empfohlene Tutorials (Reihenfolge beachten) */
export const WEEK_TUTORIALS = {
  1: [
    {
      id: "python-typing",
      title: "Python Type Hints (Real Python)",
      url: "https://realpython.com/python-type-checking/",
      type: "article",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Mo Block A",
      description: "Type Hints, mypy-Grundlagen — wichtig für FastAPI und sauberen Code.",
      steps: ["Abschnitt „Basic Annotations“", "„Class Members“ skimmen", "Beispiele selbst nachtippen"],
    },
    {
      id: "uv-docs",
      title: "uv — Python Package Manager",
      url: "https://docs.astral.sh/uv/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo Block B",
      description: "Schnelles Dependency-Management. Alternative: klassisches venv + pip.",
      steps: ["Installation", "`uv init` + `uv add fastapi uvicorn sklearn`", "Virtuelle Env aktivieren"],
    },
    {
      id: "git-progit",
      title: "Pro Git — Kapitel 1–3",
      url: "https://git-scm.com/book/de/v2",
      type: "book",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo Block A",
      description: "Deutsch verfügbar. Grundlagen, Branching, Remote-Repos.",
      steps: ["Kap. 1 Grundlagen", "Kap. 2 Git-Grundlagen", "Kap. 3 Branching"],
    },
    {
      id: "fastapi-tutorial",
      title: "FastAPI Official Tutorial",
      url: "https://fastapi.tiangolo.com/tutorial/",
      type: "docs",
      cost: "Kostenlos",
      duration: "4–6 h",
      when: "Di–Do",
      description: "Haupttutorial für Woche 1. Sehr gut strukturiert, sofort anwendbar.",
      steps: [
        "First Steps → Path Parameters",
        "Query Parameters → Body → Pydantic",
        "Dependencies → Error Handling",
        "Testing mit TestClient",
      ],
    },
    {
      id: "pytest-docs",
      title: "pytest Getting Started",
      url: "https://docs.pytest.org/en/stable/getting-started.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Do Block D",
      description: "Tests für `/health` und `/predict` schreiben.",
      steps: ["Installation", "Erster Test", "FastAPI TestClient Beispiel"],
    },
    {
      id: "sklearn-quickstart",
      title: "scikit-learn Quickstart",
      url: "https://scikit-learn.org/stable/getting_started.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mi Block B",
      description: "Modell trainieren + joblib/pickle speichern — Auffrischung aus Data Science.",
      steps: ["Classifier Beispiel", "Train/Test Split", "Modell mit pickle speichern"],
    },
  ],
  2: [
    {
      id: "docker-getting-started",
      title: "Docker Getting Started",
      url: "https://docs.docker.com/get-started/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo",
      description: "Images, Container, Dockerfile — Pflicht für ML-Deployment.",
      steps: ["Container starten", "Eigenes Image bauen", "Dockerfile schreiben"],
    },
    {
      id: "docker-compose",
      title: "Docker Compose Overview",
      url: "https://docs.docker.com/compose/gettingstarted/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Di",
      description: "Mehrere Services lokal starten — Vorbereitung für Woche 9.",
      steps: ["compose.yaml", "Services verknüpfen", "Env-Variablen"],
    },
    {
      id: "gh-actions",
      title: "GitHub Actions — Python CI",
      url: "https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi",
      description: "Automatisch testen bei jedem Push.",
      steps: ["Workflow YAML", "pytest Step", "Badge ins README"],
    },
    {
      id: "railway-deploy",
      title: "Railway — Deploy from GitHub",
      url: "https://docs.railway.com/guides/fastapi",
      type: "docs",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Do",
      description: "Einfaches Deployment. Alternativen: Render, Fly.io.",
      steps: ["Repo verbinden", "Start Command setzen", "Public URL testen"],
    },
    {
      id: "render-deploy",
      title: "Render — Deploy FastAPI (Alternative)",
      url: "https://render.com/docs/deploy-fastapi",
      type: "docs",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Do (Fallback)",
      description: "Falls Railway nicht klappt.",
      steps: ["Web Service anlegen", "Docker oder Python", "Health Check"],
    },
  ],
  3: [
    {
      id: "openai-api",
      title: "OpenAI API Reference — Chat",
      url: "https://platform.openai.com/docs/api-reference/chat",
      type: "docs",
      cost: "Pay-per-use",
      duration: "~2 h",
      when: "Mo–Di",
      description: "Offizielle API-Docs. Budget-Limit unter Billing setzen!",
      steps: ["API Key erstellen", "Chat Completions", "Streaming", "Token Usage"],
    },
    {
      id: "openai-prompting",
      title: "OpenAI Prompt Engineering Guide",
      url: "https://platform.openai.com/docs/guides/prompt-engineering",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi",
      description: "Best Practices für System-Prompts, Few-Shot, CoT.",
      steps: ["Clear instructions", "Split complex tasks", "Few-shot examples"],
    },
    {
      id: "dlai-prompt",
      title: "DeepLearning.AI — ChatGPT Prompt Engineering",
      url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
      type: "course",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi",
      description: "Kurzer Video-Kurs mit OpenAI — sehr praxisnah.",
      steps: ["Alle 9 Lektionen", "Notebooks nachbauen"],
    },
    {
      id: "ollama",
      title: "Ollama — Get Started",
      url: "https://github.com/ollama/ollama/blob/main/docs/README.md",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Di",
      description: "LLMs lokal ohne API-Kosten — Llama 3, Mistral.",
      steps: ["Installation macOS", "`ollama pull llama3.2`", "Python ollama library"],
    },
    {
      id: "streamlit",
      title: "Streamlit Get Started",
      url: "https://docs.streamlit.io/get-started",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Do",
      description: "Schnelles UI für Prompt-Lab und RAG-Demos.",
      steps: ["30-min Tutorial", "Chat-Input + Output", "Secrets für API Key"],
    },
  ],
  4: [
    {
      id: "openai-embeddings",
      title: "OpenAI Embeddings Guide",
      url: "https://platform.openai.com/docs/guides/embeddings",
      type: "docs",
      cost: "Pay-per-use",
      duration: "~1 h",
      when: "Mo",
      description: "Embedding-API, Dimensions, Cosine Similarity erklärt.",
      steps: ["Embedding erstellen", "Similarity berechnen", "Modelle vergleichen"],
    },
    {
      id: "hf-sentence-transformers",
      title: "Sentence Transformers (Open Source)",
      url: "https://www.sbert.net/docs/quickstart.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo (Alternative)",
      description: "Lokale Embeddings ohne API — z. B. `all-MiniLM-L6-v2`.",
      steps: ["Installation", "encode()", "similarity Beispiel"],
    },
    {
      id: "pinecone-embeddings",
      title: "Pinecone — What are Embeddings?",
      url: "https://www.pinecone.io/learn/series/rag/embedding-models-rag/",
      type: "article",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo Block A",
      description: "Konzeptuelle Einführung — gut vor dem Coden.",
      steps: ["Artikel lesen", "Chunking-Abschnitt notieren"],
    },
    {
      id: "chroma-docs",
      title: "ChromaDB Getting Started",
      url: "https://docs.trychroma.com/getting-started",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi",
      description: "Einfache lokale Vektordatenbank — gut für Einsteiger.",
      steps: ["Persistent Client", "Collection anlegen", "Query mit n_results"],
    },
    {
      id: "qdrant-docs",
      title: "Qdrant Quickstart (Alternative)",
      url: "https://qdrant.tech/documentation/quick-start/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi (Alternative)",
      description: "Production-tauglicher — später in Woche 9 mit Docker.",
      steps: ["Docker starten", "Python Client", "Upsert + Search"],
    },
    {
      id: "langchain-splitters",
      title: "LangChain Text Splitters",
      url: "https://python.langchain.com/docs/how_to/recursive_text_splitter/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Di",
      description: "Chunk-Größe & Overlap — auch ohne LangChain-RAG nutzbar.",
      steps: ["RecursiveCharacterTextSplitter", "chunk_size/overlap testen"],
    },
    {
      id: "pypdf",
      title: "pypdf — PDF Text extrahieren",
      url: "https://pypdf.readthedocs.io/en/stable/user/extract-text.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Di Block B",
      description: "PDFs für dein Doc-Set parsen.",
      steps: ["Installation", "Seitenweise Text", "Metadaten (Seitenzahl)"],
    },
  ],
  5: [
    {
      id: "llamaindex-starter",
      title: "LlamaIndex — Starter Tutorial",
      url: "https://docs.llamaindex.ai/en/stable/getting_started/starter_example/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo (empfohlen)",
      description: "RAG-fokussiert, klarer Einstieg. Wähle EIN Framework für den Plan.",
      steps: ["Starter Example", "Custom Documents", "Query Engine"],
    },
    {
      id: "langchain-rag",
      title: "LangChain — RAG Tutorial (Alternative)",
      url: "https://python.langchain.com/docs/tutorials/rag/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo (Alternative)",
      description: "Offizielles RAG-Tutorial — nur wenn du LangChain statt LlamaIndex wählst.",
      steps: ["Indexing", "Retrieval", "Generation"],
    },
    {
      id: "hf-nlp-course",
      title: "Hugging Face NLP Course — Ch. 1–2",
      url: "https://huggingface.co/learn/nlp-course/chapter1/1",
      type: "course",
      cost: "Kostenlos",
      duration: "~3 h",
      when: "Mo Block A (Hintergrund)",
      description: "Transformer-Grundlagen — hilft beim Verstehen, nicht beim Copy-Paste.",
      steps: ["Ch.1 Transformer Models", "Ch.2 Pipeline & Tokenizer skim"],
    },
    {
      id: "llamaindex-citations",
      title: "LlamaIndex — Citations / Source Nodes",
      url: "https://docs.llamaindex.ai/en/stable/module_guides/querying/response_synthesizers/response_synthesizers/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mi",
      description: "Quellenangaben in Antworten einbauen.",
      steps: ["source_nodes auslesen", "In Prompt/Antwort anzeigen"],
    },
  ],
  6: [
    {
      id: "llamaindex-retrieval",
      title: "LlamaIndex — Advanced Retrieval",
      url: "https://docs.llamaindex.ai/en/stable/optimizing/advanced_retrieval/advanced_retrieval/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo–Mi",
      description: "Hybrid, Reranking, Query Transformations.",
      steps: ["Hybrid Search", "Query Fusion", "Parent Document Retriever"],
    },
    {
      id: "pinecone-hybrid",
      title: "Hybrid Search Explained (Pinecone)",
      url: "https://www.pinecone.io/learn/hybrid-search-intro/",
      type: "article",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo Block A",
      description: "Warum BM25 + Vector zusammen besser sind.",
      steps: ["Artikel", "RRF Konzept notieren"],
    },
    {
      id: "rank-bm25",
      title: "rank_bm25 Python Library",
      url: "https://github.com/dorianbrown/rank_bm25",
      type: "tool",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo Block B",
      description: "BM25 in Python — für Hybrid Search.",
      steps: ["Installation", "Index auf Chunks", "Scores mit Vector fusionieren"],
    },
    {
      id: "hyde-paper",
      title: "HyDE — Hypothetical Document Embeddings",
      url: "https://arxiv.org/abs/2212.10496",
      type: "article",
      cost: "Kostenlos",
      duration: "~20 min skim",
      when: "Mi",
      description: "Query-Transformation — Abstract + LlamaIndex HyDE Modul.",
      steps: ["Abstract lesen", "In Framework implementieren"],
    },
  ],
  7: [
    {
      id: "ragas",
      title: "RAGAS Documentation",
      url: "https://docs.ragas.io/en/stable/getstarted/quickstart/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Di",
      description: "Standard für RAG-Evaluation — Faithfulness, Context Precision.",
      steps: ["Installation", "Dataset anlegen", "evaluate() ausführen", "Ergebnisse interpretieren"],
    },
    {
      id: "langfuse",
      title: "Langfuse — Quickstart",
      url: "https://langfuse.com/docs/get-started",
      type: "docs",
      cost: "Free Tier",
      duration: "~1,5 h",
      when: "Do",
      description: "Tracing & Logging für LLM/RAG-Apps.",
      steps: ["Account", "Python SDK", "Traces für Retrieval + Generation"],
    },
    {
      id: "evidently-rag",
      title: "Evidently AI — RAG Evaluation Guide",
      url: "https://www.evidentlyai.com/llm-guide/rag-evaluation",
      type: "article",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Mo",
      description: "Welche Metriken wann sinnv sind — vor RAGAS lesen.",
      steps: ["Metriken-Übersicht", "Eigenes Eval-Set planen"],
    },
  ],
  8: [
    {
      id: "openai-function-calling",
      title: "OpenAI Function Calling",
      url: "https://platform.openai.com/docs/guides/function-calling",
      type: "docs",
      cost: "Pay-per-use",
      duration: "~2 h",
      when: "Mo–Di",
      description: "Basis für Agents und Tool Use.",
      steps: ["Tool Schema definieren", "Model ruft Function", "Result zurück ans Model"],
    },
    {
      id: "dlai-functions",
      title: "DeepLearning.AI — Functions, Tools and Agents",
      url: "https://www.deeplearning.ai/short-courses/functions-tools-agents-langchain/",
      type: "course",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mo",
      description: "LangChain Agents — Konzepte übertragbar auf LlamaIndex.",
      steps: ["Alle Lektionen", "Tool-Definition nachbauen"],
    },
    {
      id: "tavily",
      title: "Tavily Search API",
      url: "https://docs.tavily.com/",
      type: "docs",
      cost: "Free Tier",
      duration: "~45 min",
      when: "Mi",
      description: "Websuche als Agent-Tool — einfacher als Scraping.",
      steps: ["API Key", "search() Wrapper", "Als Tool registrieren"],
    },
    {
      id: "llamaindex-agents",
      title: "LlamaIndex — Agents",
      url: "https://docs.llamaindex.ai/en/stable/module_guides/deploying/agents/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Di–Do",
      description: "Agent mit mehreren Tools in LlamaIndex.",
      steps: ["OpenAI Agent", "Custom Tools", "Max iterations"],
    },
  ],
  9: [
    {
      id: "fastapi-async",
      title: "FastAPI — Async / Concurrency",
      url: "https://fastapi.tiangolo.com/async/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Fr",
      description: "Parallele Requests für bessere Latenz.",
      steps: ["async def Endpoints", "await für I/O"],
    },
    {
      id: "redis-py",
      title: "redis-py Getting Started",
      url: "https://redis.readthedocs.io/en/stable/examples.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Di",
      description: "Caching-Layer für Embeddings und Responses.",
      steps: ["Docker Redis", "set/get mit TTL", "Cache-Key aus Query-Hash"],
    },
    {
      id: "slowapi",
      title: "SlowAPI — Rate Limiting für FastAPI",
      url: "https://slowapi.readthedocs.io/en/latest/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Mi",
      description: "Einfaches Rate Limiting pro IP.",
      steps: ["Installation", "Limiter auf /ask", "429 Response testen"],
    },
  ],
  10: [
    {
      id: "python-docx",
      title: "python-docx — DOCX lesen",
      url: "https://python-docx.readthedocs.io/en/latest/user/quickstart.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo",
      description: "Word-Dokumente für Multi-Format Upload.",
      steps: ["Text extrahieren", "In Chunk-Pipeline einbinden"],
    },
    {
      id: "loom",
      title: "Loom — Demo Video aufnehmen",
      url: "https://www.loom.com/",
      type: "tool",
      cost: "Free Tier",
      duration: "~30 min",
      when: "Fr",
      description: "5-Min Walkthrough für README — Recruiter schauen das gern.",
      steps: ["Screen + Mic", "Upload Flow → Frage → Quellen", "Link ins README"],
    },
  ],
  11: [
    {
      id: "github-readme-guide",
      title: "GitHub — About READMEs",
      url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo–Mi",
      description: "Best Practices für Portfolio-Repos.",
      steps: ["Struktur", "Badges", "Screenshots/GIFs"],
    },
    {
      id: "mermaid",
      title: "Mermaid — Diagramme in Markdown",
      url: "https://mermaid.js.org/intro/getting-started.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Di",
      description: "Architektur-Diagramme direkt im README.",
      steps: ["flowchart Syntax", "RAG-Pipeline zeichnen"],
    },
  ],
  12: [
    {
      id: "interview-rag",
      title: "Pinecone — RAG Interview Questions",
      url: "https://www.pinecone.io/learn/series/rag/",
      type: "article",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo",
      description: "RAG-Serie als Interview-Vorbereitung durchlesen.",
      steps: ["RAG 101", "Chunking", "Evaluation Artikel"],
    },
    {
      id: "fastapi-testclient",
      title: "FastAPI Testing — Recap",
      url: "https://fastapi.tiangolo.com/tutorial/testing/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Di",
      description: "Live-Coding im Interview — Route schnell schreiben + testen.",
      steps: ["TestClient", "POST test", "Mock LLM optional"],
    },
  ],
};

/** Optionale Ergänzungen — nur bei Bedarf, nicht Pflicht zum Plan */
export const GLOBAL_SUPPLEMENTS = [
  {
    id: "simon-willison-llms",
    title: "Simon Willison — LLM Blog",
    url: "https://simonwillison.net/tags/llms/",
    type: "article",
    cost: "Kostenlos",
    duration: "Nach Bedarf",
    description: "Praxisnahe Tipps zu RAG, Debugging, Tools und Kosten — ergänzt offizielle Docs ideal.",
    steps: [
      "2–3 Artikel pro Woche lesen (nicht alles)",
      "Besonders: RAG, Prompting, Tool-Use Tags",
      "Interessante Patterns in deine Projekte übernehmen",
    ],
  },
  {
    id: "anthropic-overview",
    title: "Anthropic — Build with Claude (Übersicht)",
    url: "https://docs.anthropic.com/en/docs/intro",
    type: "docs",
    cost: "Kostenlos",
    duration: "~30 min",
    description: "Zweite LLM-Perspektive neben OpenAI — hilfreich für Interviews und Tool-Design.",
    steps: ["Docs-Überblick", "Später: Prompting + Tool Use vertiefen"],
  },
];

export const WEEK_SUPPLEMENTS = {
  3: [
    {
      id: "anthropic-prompting",
      title: "Anthropic — Prompt Engineering",
      url: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Nach OpenAI Prompting Guide",
      description: "Alternative Best Practices — Chain-of-Thought, Beispiele, klare Rollen.",
      steps: ["Overview lesen", "Mit deinem Prompt-Lab vergleichen", "1 Prompt mit beiden Ansätzen testen"],
    },
  ],
  4: [
    {
      id: "pinecone-rag-101",
      title: "Pinecone — RAG 101 (komplette Serie)",
      url: "https://www.pinecone.io/learn/series/rag/",
      type: "article",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Wenn Embeddings/Chunking unklar",
      description: "Ganzheitliche RAG-Einführung in Artikeln — sehr gut vor Woche 5.",
      steps: ["RAG 101", "Chunking Strategies", "Retrieval Artikel"],
    },
  ],
  5: [
    {
      id: "dlai-chat-with-data",
      title: "DeepLearning.AI — LangChain: Chat with Your Data",
      url: "https://www.deeplearning.ai/short-courses/langchain-chat-with-your-data/",
      type: "course",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Parallel zu Woche 5",
      description: "Video-Kurs: RAG End-to-End — gut als roter Faden neben LlamaIndex-Docs.",
      steps: ["Alle Lektionen", "Konzepte mit deinem Doc-Bot vergleichen"],
    },
  ],
  6: [
    {
      id: "pinecone-chunking",
      title: "Pinecone — Chunking Strategies for LLM Applications",
      url: "https://www.pinecone.io/learn/chunking-strategies/",
      type: "article",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Vor Hybrid-Search Experimenten",
      description: "Vertiefung zu Fixed/Semantic/Parent-Child — direkt für dein A/B im README.",
      steps: ["Artikel lesen", "Eine Strategie mehr in deinem Bot testen"],
    },
  ],
  7: [
    {
      id: "dlai-advanced-rag",
      title: "DeepLearning.AI — Building and Evaluating Advanced RAG",
      url: "https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/",
      type: "course",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Parallel zu RAGAS",
      description: "Evaluation & Advanced Retrieval im Video — ergänzt RAGAS-Docs perfekt.",
      steps: ["Kurs durcharbeiten", "Eval-Ideen in dein Test-Set übernehmen"],
    },
  ],
  8: [
    {
      id: "anthropic-tool-use",
      title: "Anthropic — Tool Use (Function Calling)",
      url: "https://docs.anthropic.com/en/docs/build-with-claude/tool-use",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Neben OpenAI Function Calling",
      description: "Zweiter Blick auf Tool-Schemas und Agent-Patterns.",
      steps: ["Tool-Definition Docs", "Mit deinem Agent-Design vergleichen"],
    },
  ],
  10: [
    {
      id: "hf-peft",
      title: "Hugging Face — PEFT / LoRA Quickstart",
      url: "https://huggingface.co/docs/peft/quicktour",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Optional — nur wenn du Fine-Tuning erwähnen willst",
      description: "Kompakte Einführung in LoRA — für Interviews „RAG vs. Fine-Tuning“.",
      steps: ["Quicktour lesen", "Kein Pflicht-Projekt — Konzept reicht oft"],
    },
  ],
};

export function getWeekTutorials(weekNum) {
  return WEEK_TUTORIALS[weekNum] || [];
}

export function getWeekSupplements(weekNum) {
  return WEEK_SUPPLEMENTS[weekNum] || [];
}

export function getGlobalSupplements() {
  return GLOBAL_SUPPLEMENTS;
}

export function renderTutorialCard(t) {
  const typeLabel = TUTORIAL_TYPES[t.type] || t.type;
  const steps =
    t.steps && t.steps.length
      ? `<ol class="tutorial-steps">${t.steps.map((s) => `<li>${s}</li>`).join("")}</ol>`
      : "";
  return {
    html: `
      <article class="tutorial-card">
        <div class="tutorial-header">
          <span class="tutorial-type">${typeLabel}</span>
          <span class="tutorial-meta">${t.cost} · ${t.duration}</span>
        </div>
        <h4><a href="${t.url}" target="_blank" rel="noopener">${t.title}</a></h4>
        ${t.when ? `<p class="tutorial-when"><strong>Wann:</strong> ${t.when}</p>` : ""}
        <p class="tutorial-desc">${t.description}</p>
        ${steps ? `<p class="tutorial-steps-label"><strong>So lernen:</strong></p>${steps.replace(/<ol class="tutorial-steps">/, '<ol class="tutorial-steps">')}` : ""}
      </article>`,
  };
}
