/** Detaillierte Lernressourcen — 12-Wochen ML/DL-Sprint (zollsoft / Medizin-KI) */

export const TUTORIAL_TYPES = {
  docs: "Dokumentation",
  video: "Video",
  course: "Kurs",
  book: "Buch",
  article: "Artikel",
  tool: "Tool",
};

export const GLOBAL_RESOURCES = [
  {
    id: "real-python",
    title: "Real Python",
    url: "https://realpython.com/",
    type: "article",
    cost: "Teils kostenlos",
    duration: "Nach Bedarf",
    description:
      "Hochwertige Python-Artikel — Type Hints, pytest, FastAPI. Gezielt nach Thema suchen.",
  },
  {
    id: "sklearn-userguide",
    title: "scikit-learn User Guide",
    url: "https://scikit-learn.org/stable/user_guide.html",
    type: "docs",
    cost: "Kostenlos",
    duration: "Referenz",
    description:
      "ML-Referenz — Pipelines, Metriken, Ensembles. Begleitet Wochen 2 und 4 (Baseline + Eval).",
  },
  {
    id: "pytorch-hub",
    title: "PyTorch Tutorials",
    url: "https://pytorch.org/tutorials/",
    type: "docs",
    cost: "Kostenlos",
    duration: "Nach Bedarf",
    description:
      "Offizielle PyTorch-Tutorials — Training Loop, CNN, Transfer Learning (Wochen 3–5).",
  },
  {
    id: "tensorflow-docs",
    title: "TensorFlow Documentation",
    url: "https://www.tensorflow.org/tutorials",
    type: "docs",
    cost: "Kostenlos",
    duration: "Referenz",
    description:
      "TensorFlow/Keras — Pflicht-Kennnis für zollsoft; MNIST-Vergleich in Woche 8.",
  },
  {
    id: "zollsoft-jobs",
    title: "zollsoft — ML/DL Stellen",
    url: "https://zollsoft.de/jobs/softwareentwicklung/softwareentwickler-machine-deep-learning/",
    type: "article",
    cost: "Kostenlos",
    duration: "~30 min",
    description:
      "Stellenprofil ML/DL bei zollsoft — Spracherkennung, Lesionsklassifikation, volle Pipeline.",
  },
];

/** Woche → empfohlene Tutorials (Reihenfolge beachten) */
export const WEEK_TUTORIALS = {
  1: [
    {
      id: "uv-docs",
      title: "uv — Python Package Manager",
      url: "https://docs.astral.sh/uv/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo — Theorie",
      description:
        "Schnelles Dependency-Management mit uv — Basis für alle ML-Repos im Sprint.",
      steps: [
        "uv installieren",
        "`uv init` + `uv add pytest fastapi`",
        "Virtuelle Umgebung aktivieren und testen",
      ],
    },
    {
      id: "python-typing",
      title: "Python — Type Hints",
      url: "https://docs.python.org/3/library/typing.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Mo — Hands-on",
      description:
        "Type Hints für wartbaren Medizin-ML-Code — Pflicht bei FastAPI und pytest.",
      steps: [
        "Basic Annotations (str, int, list)",
        "Optional, Union, TypedDict skim",
        "In app/schemas.py anwenden",
      ],
    },
    {
      id: "fastapi-tutorial",
      title: "FastAPI — Offizielles Tutorial",
      url: "https://fastapi.tiangolo.com/tutorial/",
      type: "docs",
      cost: "Kostenlos",
      duration: "4–6 h",
      when: "Di — Theorie",
      description:
        "REST-API-Grundlagen — später für ML-, CV- und Speech-Endpunkte (zollsoft-Kern).",
      steps: [
        "First Steps + Path/Query",
        "Request Body + Pydantic",
        "TestClient für /health",
      ],
    },
    {
      id: "pytest-docs",
      title: "pytest — Getting Started",
      url: "https://docs.pytest.org/en/stable/getting-started.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mi — Theorie",
      description: "Unit-Tests von Anfang an — jede API und jedes Modell braucht Tests.",
      steps: [
        "Installation + erster Test",
        "Fixtures für TestClient",
        "5 Tests für /health und Schemas",
      ],
    },
    {
      id: "git-progit",
      title: "Pro Git — Kapitel 1–3",
      url: "https://git-scm.com/book/de/v2",
      type: "book",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mi — Hands-on",
      description: "Git auf Deutsch — Branching und Remote für Portfolio-Repos.",
      steps: [
        "Kap. 1 Grundlagen",
        "Kap. 2 Git-Grundlagen",
        "Kap. 3 Branching + PR üben",
      ],
    },
    {
      id: "real-python",
      title: "Real Python — FastAPI & pytest",
      url: "https://realpython.com/fastapi-python/",
      type: "article",
      cost: "Teils kostenlos",
      duration: "~1,5 h",
      when: "Do — Theorie",
      description:
        "Praxisnahe Erklärung zu FastAPI und Tests — ergänzt offizielle Docs.",
      steps: [
        "FastAPI-Artikel skimmen",
        "pytest-Artikel vergleichen",
        "1 Pattern ins Repo übernehmen",
      ],
    },
  ],
  2: [
    {
      id: "sklearn-quickstart",
      title: "scikit-learn — Quickstart",
      url: "https://scikit-learn.org/stable/getting_started.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo — Theorie",
      description:
        "Erstes Klassifikationsmodell — Baseline vor Deep Learning (Recruiter-Häkchen).",
      steps: [
        "Classifier-Beispiel durcharbeiten",
        "Train/Test Split",
        "Baseline-F1 notieren",
      ],
    },
    {
      id: "sklearn-pipeline",
      title: "scikit-learn — Pipelines",
      url: "https://scikit-learn.org/stable/modules/compose.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo — Hands-on",
      description: "Pipeline + ColumnTransformer — kein Data Leakage in medizinischen Tabular-Daten.",
      steps: [
        "Pipeline mit Preprocessing",
        "ColumnTransformer für gemischte Features",
        "End-to-End fit/predict",
      ],
    },
    {
      id: "sklearn-metrics",
      title: "scikit-learn — Model Evaluation",
      url: "https://scikit-learn.org/stable/modules/model_evaluation.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Di — Theorie",
      description:
        "Precision, Recall, F1, ROC — medizinisch relevant (Melanom, Diagnose-Support).",
      steps: [
        "classification_report",
        "Confusion Matrix plotten",
        "ROC-Kurve + AUC",
      ],
    },
    {
      id: "statquest-metrics",
      title: "StatQuest — Sensitivity, Specificity & ROC",
      url: "https://www.youtube.com/watch?v=vP06aOzhb2w",
      type: "video",
      cost: "Kostenlos",
      duration: "~25 min",
      when: "Di — Hands-on",
      description:
        "Metriken visuell verstehen — essentiell für zollsoft-Gespräche und HAM10000-Eval.",
      steps: [
        "Video ansehen",
        "Sensitivity vs. Specificity notieren",
        "Mit sklearn-Metriken verknüpfen",
      ],
    },
    {
      id: "docker-getting-started",
      title: "Docker — Getting Started",
      url: "https://docs.docker.com/get-started/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Do — Theorie",
      description: "Container-Grundlagen — Pflicht für ML-API-Deploy (Woche 2 Meilenstein).",
      steps: [
        "Container starten",
        "Image bauen",
        "Dockerfile für FastAPI schreiben",
      ],
    },
    {
      id: "railway-deploy",
      title: "Railway — FastAPI deployen",
      url: "https://docs.railway.com/guides/fastapi",
      type: "docs",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Fr — Projekt",
      description: "Cloud-Deploy für ML-API — Live-URL im README (Recruiter-Check).",
      steps: [
        "Repo mit Railway verbinden",
        "Deploy + Logs prüfen",
        "Public URL mit curl testen",
      ],
    },
  ],
  3: [
    {
      id: "pytorch-60min",
      title: "PyTorch — Deep Learning in 60 Minutes",
      url: "https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html",
      type: "course",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo — Theorie",
      description:
        "Tensors und autograd — Einstieg Deep Learning (zollsoft-Pflicht: PyTorch).",
      steps: [
        "Tensors + Operationen",
        "Autograd verstehen",
        "MNIST-Datensatz laden",
      ],
    },
    {
      id: "pytorch-training",
      title: "PyTorch — Training Loop",
      url: "https://pytorch.org/tutorials/beginner/introyt/trainingyt.html",
      type: "video",
      cost: "Kostenlos",
      duration: "~3 h",
      when: "Di–Mi",
      description:
        "Manueller Training Loop — 5 Schritte auswendig für Interview erklären können.",
      steps: [
        "DataLoader einrichten",
        "Forward + Loss + Backward",
        "Validation + Checkpoint speichern",
      ],
    },
    {
      id: "cs231n-cnn",
      title: "CS231n — Convolutional Networks",
      url: "https://cs231n.github.io/convolutional-networks/",
      type: "article",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Do — Theorie",
      description:
        "CNN-Theorie — Conv, Pool, FC. Vorbereitung HAM10000 / Melanom-Klassifikation (W4).",
      steps: [
        "Conv-Layer verstehen",
        "Pooling + Architektur skizzieren",
        "Mit PyTorch nn.Conv2d verbinden",
      ],
    },
    {
      id: "docker-compose",
      title: "Docker Compose — Getting Started",
      url: "https://docs.docker.com/compose/gettingstarted/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Fr — optional Vorbereitung",
      description:
        "Multi-Service-Stack — Vorbereitung für CV- und Speech-Deploy (W5, W7).",
      steps: [
        "compose.yaml anlegen",
        "API + Volume für Modelle",
        "Lokalen Stack testen",
      ],
    },
  ],
  4: [
    {
      id: "ham10000",
      title: "HAM10000 — Hautläsionen-Dataset",
      url: "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T",
      type: "tool",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mo — Theorie",
      description:
        "Medizinisches CV-Dataset — direkt relevant für zollsoft Lesionsklassifikation.",
      steps: [
        "Download + Metadaten lesen",
        "Klassenverteilung (EDA)",
        "Stratified Train/Val Split",
      ],
    },
    {
      id: "pytorch-transfer",
      title: "PyTorch — Transfer Learning",
      url: "https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html",
      type: "course",
      cost: "Kostenlos",
      duration: "~3 h",
      when: "Di — Hands-on",
      description: "ResNet18 fine-tunen — freeze vs. unfreeze für HAM10000.",
      steps: [
        "ResNet18 mit torchvision laden",
        "Classifier-Head ersetzen",
        "Fine-tuning starten",
      ],
    },
    {
      id: "pytorch-augment",
      title: "PyTorch — Transforms & Augmentation",
      url: "https://pytorch.org/vision/stable/transforms.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi — Hands-on",
      description:
        "Medical Augmentation vorsichtig — Rotation, Flip, ColorJitter gegen Overfitting.",
      steps: [
        "Compose([Resize, Normalize])",
        "RandomHorizontalFlip + Rotation",
        "Augmentierte Bilder visualisieren",
      ],
    },
    {
      id: "sklearn-metrics",
      title: "scikit-learn — Model Evaluation (CV-Eval)",
      url: "https://scikit-learn.org/stable/modules/model_evaluation.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Do — Theorie",
      description:
        "Per-Class Precision/Recall für unbalancierte HAM10000-Klassen — Recall in Medizin.",
      steps: [
        "classification_report pro Klasse",
        "Confusion Matrix für Melanom",
        "Failure Cases sammeln",
      ],
    },
    {
      id: "shap-docs",
      title: "SHAP — Explainable AI Intro",
      url: "https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20SHAP.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h skim",
      when: "Fr — optional",
      description:
        "XAI-Vorschau — später in W9 vertiefen; gut für medizinische Modell-Erklärbarkeit.",
      steps: [
        "Notebook skimmen",
        "Idee Feature Importance vs. SHAP",
        "Für Signature-Projekt merken",
      ],
    },
  ],
  5: [
    {
      id: "pytorch-inference",
      title: "PyTorch — Saving & Loading Models",
      url: "https://pytorch.org/tutorials/beginner/saving_loading_models.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mo — Theorie",
      description:
        "Inference mit .pt — torch.no_grad, state_dict für Production-CV-API.",
      steps: [
        "best.pt laden",
        "model.eval() + torch.no_grad()",
        "Preprocessing + softmax top-k",
      ],
    },
    {
      id: "fastapi-tutorial",
      title: "FastAPI — File Upload & Bild-API",
      url: "https://fastapi.tiangolo.com/tutorial/request-files/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Di — Hands-on",
      description: "UploadFile für Bilder — POST /predict/image für zollsoft-CV-Demo.",
      steps: [
        "Request Files Kapitel",
        "UploadFile + PIL/torchvision",
        "Pydantic Response Schema",
      ],
    },
    {
      id: "docker-getting-started",
      title: "Docker — Production Dockerfile",
      url: "https://docs.docker.com/get-started/workshop/09_image_best/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mi — Projekt",
      description: "Schlankes Image für CV-Modell — Multi-Stage optional.",
      steps: [
        "Dockerfile mit Modell-Volume",
        "docker build + run",
        "Größe und Startzeit prüfen",
      ],
    },
    {
      id: "docker-compose",
      title: "Docker Compose — CV-Stack",
      url: "https://docs.docker.com/compose/gettingstarted/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mi — Hands-on",
      description: "API + Modell-Volume in compose — lokaler E2E-Test vor Deploy.",
      steps: [
        "compose.yaml mit volumes",
        "docker compose up",
        "10 Testbilder per curl",
      ],
    },
    {
      id: "railway-deploy",
      title: "Railway — CV-API live",
      url: "https://docs.railway.com/guides/fastapi",
      type: "docs",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Do — Deploy",
      description: "Live CV-URL + Demo-GIF im README — Hauptprojekt für zollsoft-Gespräch.",
      steps: [
        "Deploy mit größerem Image",
        "Extern curl testen",
        "README mit Live-Link + GIF",
      ],
    },
  ],
  6: [
    {
      id: "spacy-101",
      title: "spaCy 101",
      url: "https://spacy.io/usage/spacy-101",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo — Theorie",
      description:
        "NLP-Pipeline mit spaCy — de_core_news_sm für medizinische Texte (Vorbereitung Speech/NLP).",
      steps: [
        "Installation + de Modell",
        "nlp() Pipeline durchlaufen",
        "displacy für NER-Demo",
      ],
    },
    {
      id: "spacy-ner",
      title: "spaCy — Named Entity Recognition",
      url: "https://spacy.io/usage/linguistic-features#named-entities",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Di — Hands-on",
      description: "NER auf deutschen Texten — Entities für klinische Snippets extrahieren.",
      steps: [
        "doc.ents auslesen",
        "10 Beispieltexte annotieren",
        "JSON-Export bauen",
      ],
    },
    {
      id: "spacy-custom",
      title: "spaCy — EntityRuler & Custom NER",
      url: "https://spacy.io/usage/linguistic-features#entityruler",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mi — Projekt",
      description:
        "Medizinische Abkürzungen und Begriffe per EntityRuler — ohne großes Training.",
      steps: [
        "EntityRuler Patterns definieren",
        "In Pipeline einhängen",
        "Kleines Eval-Set testen",
      ],
    },
    {
      id: "linux-survival",
      title: "Linux Survival",
      url: "https://linuxsurvival.com/",
      type: "course",
      cost: "Kostenlos",
      duration: "~1 h skim",
      when: "Do — optional",
      description:
        "Terminal-Grundlagen — Vorbereitung W8 Pipeline-Skripte und Server-Deploy.",
      steps: [
        "Lessons 1–2 durcharbeiten",
        "grep, ls, chmod üben",
        "5 Befehle notieren",
      ],
    },
  ],
  7: [
    {
      id: "whisper-docs",
      title: "OpenAI Whisper — Dokumentation",
      url: "https://github.com/openai/whisper",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mo — Theorie",
      description:
        "Whisper-Architektur und Model Sizes — zollsoft-Kern: Spracherkennung für Ärzte.",
      steps: [
        "README + Model-Tabelle lesen",
        "base vs. small für DE wählen",
        "3 DE-Audio-Samples transkribieren",
      ],
    },
    {
      id: "faster-whisper",
      title: "faster-whisper — Schnelle Inference",
      url: "https://github.com/SYSTRAN/faster-whisper",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo — Hands-on",
      description: "CTranslate2-basiert — produktionsnahe Latenz für /transcribe API.",
      steps: [
        "pip install faster-whisper",
        "WhisperModel transcribe()",
        "Latenz für 1-min Audio messen",
      ],
    },
    {
      id: "fastapi-tutorial",
      title: "FastAPI — Audio Upload",
      url: "https://fastapi.tiangolo.com/tutorial/request-files/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Di — Projekt",
      description: "POST /transcribe mit UploadFile — Temp-Files und Timeout.",
      steps: [
        "Audio-Upload Endpoint",
        "Background task oder sync",
        "3 API-Tests mit pytest",
      ],
    },
    {
      id: "docker-compose",
      title: "Docker Compose — Speech-Stack",
      url: "https://docs.docker.com/compose/gettingstarted/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Do — Deploy",
      description: "Lokaler Speech-Service — Modell-Cache und API in compose.",
      steps: [
        "compose mit Whisper-Volume",
        "Stack starten",
        "README Speech-Abschnitt",
      ],
    },
  ],
  8: [
    {
      id: "linux-survival",
      title: "Linux Survival — Terminal",
      url: "https://linuxsurvival.com/",
      type: "course",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mo — Theorie",
      description: "grep, find, Pipes — download.sh für Daten-Pipeline (zollsoft: volle Pipeline).",
      steps: [
        "Lessons 1–4",
        "grep + find üben",
        "Pipeline-Skript chmod +x",
      ],
    },
    {
      id: "bash-guide",
      title: "GNU Bash — Einführung",
      url: "https://www.gnu.org/software/bash/manual/html_node/index.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo — Hands-on",
      description: "Shebang, Variablen, Exit-Codes — robuste Bash-Skripte für ML-Pipelines.",
      steps: [
        "Simples download.sh",
        "Args ($1, $2)",
        "Exit codes + set -e",
      ],
    },
    {
      id: "tensorflow-quickstart",
      title: "TensorFlow — Quickstart for Beginners",
      url: "https://www.tensorflow.org/tutorials/quickstart/beginner",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Di — Theorie",
      description:
        "TF/Keras Einstieg — gleiches Problem wie PyTorch W3; zollsoft nennt TensorFlow explizit.",
      steps: [
        "Quickstart durcharbeiten",
        "MNIST oder Tabular",
        "Notiz PT vs. TF",
      ],
    },
    {
      id: "keras-guide",
      title: "TensorFlow — Keras Guide",
      url: "https://www.tensorflow.org/guide/keras",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Di — Hands-on",
      description: "Sequential API, compile/fit — Interview: Keras in 2 Min erklären.",
      steps: [
        "Sequential model",
        "compile + fit",
        "model.save als .h5",
      ],
    },
    {
      id: "mlflow-quickstart",
      title: "MLflow — Quickstart",
      url: "https://mlflow.org/docs/latest/getting-started/intro-quickstart/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mi — Projekt",
      description: "Experiment Tracking — params, metrics für CV- und sklearn-Runs.",
      steps: [
        "mlflow ui starten",
        "3 Runs loggen",
        "Screenshot ins README",
      ],
    },
    {
      id: "mlflow-models",
      title: "MLflow — Models & Registry",
      url: "https://mlflow.org/docs/latest/models.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1,5 h",
      when: "Mi — Hands-on",
      description: "log_model + Registry — bestes Modell für Signature-Projekt registrieren.",
      steps: [
        "mlflow.pytorch.log_model",
        "Best Run registrieren",
        "Load für Inference testen",
      ],
    },
  ],
  9: [
    {
      id: "mermaid",
      title: "Mermaid — Flowcharts",
      url: "https://mermaid.js.org/syntax/flowchart.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Mo — Spec",
      description:
        "Pipeline-Diagramm für Signature-Projekt — Daten → Train → API → Deploy (zollsoft-Wording).",
      steps: [
        "flowchart TD zeichnen",
        "In README einbinden",
        "Mit Issue-Liste abgleichen",
      ],
    },
    {
      id: "ham10000",
      title: "HAM10000 — Daten für Signature",
      url: "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T",
      type: "tool",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Di — Daten",
      description: "Datenakquise und Preprocessing für Signature CV — oder Whisper-Samples für Speech.",
      steps: [
        "Datenpfad dokumentieren",
        "Preprocessing-Tests",
        "EDA aktualisieren",
      ],
    },
    {
      id: "whisper-docs",
      title: "Whisper — Speech Signature Option",
      url: "https://github.com/openai/whisper",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Di — optional Speech-Pfad",
      description: "Alternative zu HAM10000 — Signature Speech mit Whisper-Datenpipeline.",
      steps: [
        "Audio-Samples sammeln",
        "Transkript-Qualität prüfen",
        "Pipeline-Spec anpassen",
      ],
    },
    {
      id: "pytorch-transfer",
      title: "PyTorch — Transfer Learning (Retrain)",
      url: "https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html",
      type: "course",
      cost: "Kostenlos",
      duration: "~3 h",
      when: "Mi — Training",
      description: "Full Train für Signature — MLflow-Logging parallel.",
      steps: [
        "Hyperparameter festlegen",
        "Training + Val-Metriken",
        "Checkpoint + MLflow Run",
      ],
    },
    {
      id: "shap-docs",
      title: "SHAP — Error Analysis",
      url: "https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20SHAP.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Do — Eval",
      description: "20 Failure Cases + optional SHAP — medizinische Modell-Erklärbarkeit.",
      steps: [
        "TreeExplainer oder DeepExplainer skim",
        "summary_plot für Top Features",
        "Design-Entscheidungen dokumentieren",
      ],
    },
  ],
  10: [
    {
      id: "slowapi",
      title: "SlowAPI — Rate Limiting",
      url: "https://slowapi.readthedocs.io/en/latest/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Mo — Hardening",
      description: "Rate Limit pro IP — Production-API für Signature-Projekt.",
      steps: [
        "slowapi installieren",
        "Limiter auf /predict",
        "429 Response testen",
      ],
    },
    {
      id: "fastapi-async",
      title: "FastAPI — Async Concurrency",
      url: "https://fastapi.tiangolo.com/async/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo — Hands-on",
      description: "async def für I/O-bound Inference und File-Uploads.",
      steps: [
        "async Endpoints",
        "await für schwere I/O",
        "/health und /ready trennen",
      ],
    },
    {
      id: "gh-actions",
      title: "GitHub Actions — Python CI",
      url: "https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python",
      type: "docs",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Mi — CI",
      description: "pytest CI auf allen Repos — grüne Badges im README.",
      steps: [
        "Workflow YAML anlegen",
        "pytest in CI",
        "Badge ins README",
      ],
    },
    {
      id: "railway-deploy",
      title: "Railway — Signature live",
      url: "https://docs.railway.com/guides/fastapi",
      type: "docs",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Di — Deploy",
      description: "Production Deploy Signature-API — Live-URL + externer E2E-Test.",
      steps: [
        "Production Dockerfile",
        "Deploy + Logs",
        "curl von außerhalb",
      ],
    },
    {
      id: "loom",
      title: "Loom — Demo-Video",
      url: "https://www.loom.com/",
      type: "tool",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Do — Demo",
      description: "5-Min-Walkthrough Video — CV oder Speech für Bewerbungsmappe.",
      steps: [
        "Script schreiben (Metriken + Live-Demo)",
        "Aufnehmen + Link",
        "Link im README verankern",
      ],
    },
  ],
  11: [
    {
      id: "github-readme-guide",
      title: "GitHub — About READMEs",
      url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes",
      type: "docs",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Mo — Portfolio",
      description:
        "README-Template — GIFs, Live-URLs, Metriken-Tabelle für 3 Repos (ML, CV, Speech).",
      steps: [
        "Template definieren",
        "ML-API README polieren",
        "CV + Speech README angleichen",
      ],
    },
    {
      id: "mermaid",
      title: "Mermaid — Skills & Pipeline im Profil",
      url: "https://mermaid.js.org/syntax/flowchart.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~20 min",
      when: "Do — Kompetenzprofil",
      description: "PyTorch → TF → Deploy Pipeline visualisieren für 1-Seiten-Profil.",
      steps: [
        "Skills-Flowchart",
        "In docs/kompetenz.md",
        "Match mit zollsoft-Stellenprofil",
      ],
    },
    {
      id: "zollsoft-jobs",
      title: "zollsoft — Stellenanalyse",
      url: "https://zollsoft.de/jobs/softwareentwicklung/softwareentwickler-machine-deep-learning/",
      type: "article",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Di — Bewerbung",
      description:
        "Stellenanzeige analysieren — Keywords für Anschreiben und Kompetenzprofil.",
      steps: [
        "Anforderungen markieren",
        "Projekte zuordnen (CV, Speech, Deploy)",
        "Anschreiben-Entwurf starten",
      ],
    },
    {
      id: "interview-ml",
      title: "ML Interview Questions",
      url: "https://github.com/khang072000/Machine-Learning-Interview-Questions",
      type: "article",
      cost: "Kostenlos",
      duration: "~1 h skim",
      when: "Fr — Vorbereitung W12",
      description: "Fragen-Katalog durchsehen — Vorbereitung auf 15 schriftliche Antworten.",
      steps: [
        "20 Fragen markieren",
        "Medizin-Beispiele zuordnen",
        "Top 5 für W12 priorisieren",
      ],
    },
  ],
  12: [
    {
      id: "interview-ml",
      title: "ML Interview — 15 Antworten",
      url: "https://github.com/khang072000/Machine-Learning-Interview-Questions",
      type: "article",
      cost: "Kostenlos",
      duration: "~3 h",
      when: "Mo — Interview Prep",
      description:
        "15 schriftliche Antworten mit HAM10000-, Whisper- und Deploy-Beispielen.",
      steps: [
        "docs/interview.md anlegen",
        "15 Antworten schreiben",
        "5 laut üben (Timing)",
      ],
    },
    {
      id: "zollsoft-jobs",
      title: "zollsoft — Bewerbung absenden",
      url: "https://zollsoft.de/jobs/softwareentwicklung/softwareentwickler-machine-deep-learning/",
      type: "article",
      cost: "Kostenlos",
      duration: "~2 h",
      when: "Do — Bewerbung",
      description: "PDFs + Online-Formular — Tracking für zollsoft und 5 ähnliche Stellen.",
      steps: [
        "Anschreiben + CV PDF",
        "zollsoft online bewerben",
        "Tracking-Tabelle führen",
      ],
    },
    {
      id: "loom",
      title: "Loom — Pitch üben",
      url: "https://www.loom.com/",
      type: "tool",
      cost: "Free Tier",
      duration: "~1 h",
      when: "Di–Mi — Pitch",
      description: "CV- und Speech-Projekt je 5 Min — Metriken und Live-Demo.",
      steps: [
        "CV-Pitch 3× (5 Min)",
        "Speech-Pitch 3× (5 Min)",
        "Feedback-Notizen",
      ],
    },
    {
      id: "github-readme-guide",
      title: "GitHub README — Final Check",
      url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Fr — Abschluss",
      description: "Alle Repos pinned — Links, GIFs und Metriken recruiter-ready.",
      steps: [
        "3 Repos auf GitHub pinnen",
        "Links live prüfen",
        "Mock-Interview + Reflexion",
      ],
    },
  ],
};

/** Optionale Ergänzungen — nur bei Bedarf, nicht Pflicht zum Plan */
export const GLOBAL_SUPPLEMENTS = [
  {
    id: "zollsoft-jobs",
    title: "zollsoft — ML/DL Softwareentwickler",
    url: "https://zollsoft.de/jobs/softwareentwicklung/softwareentwickler-machine-deep-learning/",
    type: "article",
    cost: "Kostenlos",
    duration: "~30 min",
    when: "Optional — jederzeit",
    description:
      "Offizielle Stellenseite — tomedo, KI-Team, Anforderungen PyTorch/TF/CV/Speech.",
    steps: [
      "Stellenprofil lesen",
      "Mit Sprint-Meilensteinen abgleichen",
      "Keywords für Bewerbung notieren",
    ],
  },
  {
    id: "ham10000-paper",
    title: "HAM10000 — Dataset Paper (Nature)",
    url: "https://www.nature.com/articles/s41597-018-0061-0",
    type: "article",
    cost: "Kostenlos",
    duration: "~45 min skim",
    when: "Optional — CV-Vertiefung",
    description:
      "Wissenschaftliche Beschreibung HAM10000 — Klassen, Labeling, klinischer Kontext Melanom.",
    steps: [
      "Abstract + Methods skimmen",
      "7 Diagnose-Kategorien notieren",
      "Im README zitieren",
    ],
  },
  {
    id: "simon-willison",
    title: "Simon Willison — Blog & Tools",
    url: "https://simonwillison.net/",
    type: "article",
    cost: "Kostenlos",
    duration: "Nach Bedarf",
    when: "Optional",
    description:
      "Praxisnahe ML/LLM-Notizen, datasette, llm CLI — Inspiration für Engineering-Kultur.",
    steps: [
      "Neueste ML-Posts skimmen",
      "1 Tool ausprobieren (optional)",
      "Engineering-Tipp fürs Portfolio",
    ],
  },
];

export const WEEK_SUPPLEMENTS = {
  4: [
    {
      id: "ham10000-paper",
      title: "HAM10000 Paper — Skim",
      url: "https://www.nature.com/articles/s41597-018-0061-0",
      type: "article",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Sa — Paper skim",
      description: "Medizinischer Kontext für Läsionsklassifikation — Sa Paper-Tag im Tagesplan.",
      steps: [
        "Abstract lesen",
        "Klassen-Definitionen notieren",
        "1 Absatz fürs README",
      ],
    },
    {
      id: "cs231n-cnn",
      title: "CS231n — CNN Vertiefung",
      url: "https://cs231n.github.io/convolutional-networks/",
      type: "article",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Optional",
      description: "CNN-Details nach W3-Intro — Filter, Receptive Field.",
      steps: [
        "Conv-Rechnung nachvollziehen",
        "Architektur-Skizze",
        "Mit ResNet vergleichen",
      ],
    },
  ],
  5: [
    {
      id: "real-python",
      title: "Real Python — Docker für Python",
      url: "https://realpython.com/python-docker/",
      type: "article",
      cost: "Teils kostenlos",
      duration: "~1,5 h",
      when: "Optional",
      description: "Alternative Dockerfile-Patterns für ML-Images mit Modell.",
      steps: [
        "Artikel skimmen",
        "Mit eigenem Dockerfile vergleichen",
        "Best Practice übernehmen",
      ],
    },
    {
      id: "mermaid",
      title: "Mermaid — CV Inference Architektur",
      url: "https://mermaid.js.org/syntax/flowchart.html",
      type: "docs",
      cost: "Kostenlos",
      duration: "~20 min",
      when: "Meilenstein",
      description: "Upload → Preprocess → ResNet → Response im README.",
      steps: [
        "Flowchart zeichnen",
        "README ergänzen",
        "5-Min-Pitch vorbereiten",
      ],
    },
  ],
  7: [
    {
      id: "faster-whisper",
      title: "faster-whisper — GPU & batch",
      url: "https://github.com/SYSTRAN/faster-whisper",
      type: "docs",
      cost: "Kostenlos",
      duration: "~45 min",
      when: "Optional",
      description: "compute_type, beam_size — Latenz für lange Diktate optimieren.",
      steps: [
        "int8 vs. float16 testen",
        "Latenz-Tabelle",
        "Interview-Notiz ASR",
      ],
    },
    {
      id: "zollsoft-jobs",
      title: "zollsoft — Spracherkennung im Profil",
      url: "https://zollsoft.de/jobs/softwareentwicklung/softwareentwickler-machine-deep-learning/",
      type: "article",
      cost: "Kostenlos",
      duration: "~15 min",
      when: "Meilenstein W7",
      description: "Speech-Meilenstein mit zollsoft-Anforderung verknüpfen — Notiz fürs Gespräch.",
      steps: [
        "Stellenprofil Speech-Abschnitt",
        "Eigene Demo verlinken",
        "1 Satz Pitch formulieren",
      ],
    },
  ],
  10: [
    {
      id: "mlflow-quickstart",
      title: "MLflow — Signature Runs Review",
      url: "https://mlflow.org/docs/latest/getting-started/intro-quickstart/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Optional",
      description: "Beste Runs aus W8/W9 im UI vergleichen — Metriken-Tabelle fürs README.",
      steps: [
        "mlflow ui öffnen",
        "Top-3 Runs vergleichen",
        "Screenshot in README",
      ],
    },
    {
      id: "docker-getting-started",
      title: "Docker — Production Checklist",
      url: "https://docs.docker.com/develop/dev-best-practices/",
      type: "docs",
      cost: "Kostenlos",
      duration: "~30 min",
      when: "Optional",
      description: "Best Practices vor finalem Signature-Deploy.",
      steps: [
        "Multi-stage skim",
        ".dockerignore prüfen",
        "Image-Größe optimieren",
      ],
    },
  ],
  12: [
    {
      id: "simon-willison",
      title: "Simon Willison — LLM Engineering",
      url: "https://simonwillison.net/tags/llms/",
      type: "article",
      cost: "Kostenlos",
      duration: "Nach Bedarf",
      when: "Optional — nach Sprint",
      description: "Optional follow-up nach Bewerbung — moderne ML-Engineering-Ideen.",
      steps: [
        "2 Posts lesen",
        "1 Idee fürs nächste Projekt",
        "Pause einplanen",
      ],
    },
    {
      id: "interview-ml",
      title: "ML Interview — Zusatzfragen",
      url: "https://github.com/khang072000/Machine-Learning-Interview-Questions",
      type: "article",
      cost: "Kostenlos",
      duration: "~1 h",
      when: "Optional",
      description: "Mock-Interview am Meilenstein — zusätzliche Fragen zu Bias und DSGVO.",
      steps: [
        "5 Ethik/DSGVO Fragen",
        "Antworten ergänzen",
        "Mock mit Timer",
      ],
    },
  ],
};

export function getWeekTutorials(weekNum) {
  return WEEK_TUTORIALS[weekNum] || [];
}

export function getWeekSupplements(weekNum) {
  return WEEK_SUPPLEMENTS[weekNum] || [];
}

export function getGlobalSupplements() {
  return GLOBAL_SUPPLEMENTS;
}
